- edxpipelines/constants.py
- edxpipelines/patterns/stages.py
@edx/pipeline-team PTAL. Small change to standardize migrations stage/job name.
> migrations stage/job now use names in constants

- edxpipelines/patterns/stages.py
- edxpipelines/patterns/tasks.py
- edxpipelines/pipelines/cd_programs_multistage.py
@edx/pipeline-team I would like to get this in for other teams working on the pipeline before the work for TE-1540. This sets up better paths to run a play (so the config files are properly loaded) and a generic migrations stage/task.
> Pathing fixes for plays and a more generic migrations stage/task.

- edxpipelines/patterns/pipelines.py
This pattern can be used to deploy IDAs. The generated pipeline will run the latest Ansible, create an AMI, run migrations, and deploy a new instance.
ECOM-5771
> Created a deployment pipeline pattern for IDAs

- edxpipelines/patterns/stages.py
@doctoryes PTAL. This will allow us to specify the directory of the configuration secure repo to support deployments of the edge, mckinsey, etc environments.
> Allow the configuration secure directory to be specified for the play stage

- edxpipelines/patterns/pipelines.py
@maxrothman @jibsheet 
I got a little overzealous in the materials changes pushing this down to the IDAs. I have reverted back these changes and added a note to switch back once I finish the materials changes for IDAs.
> Revert overzealous changes to git materials, properly tag IDA AMIs

- edxpipelines/constants.py
- edxpipelines/patterns/stages.py
- edxpipelines/pipelines/manual_verification.py
- edxpipelines/pipelines/rollback_asgs.py
@edx/pipeline-team @maxrothman PTAL.
This will ensure material SHAs are kept consistent when an ASG needs to be rolled back.
> Make ASG rollback pipelines run automatically.

- config.yml
- deploy_pipelines.py
- edxpipelines/constants.py
- edxpipelines/pipelines/cd_edxapp.py
- edxpipelines/pipelines/prerelease_materials.py
- edxpipelines/tests/test_utils.py
- edxpipelines/utils.py
https://openedx.atlassian.net/browse/TE-1789
Companion PR:
https://github.com/edx-ops/gomatic-secure/pull/70
Makes changes needed to create the pipeline system which builds production AMIs for edx/edge while the stage B/M/D process is occurring, speeding up eventual production deployments.
The existing edxapp pipeline system for deployments is preserved, as it's a critical piece of infrastructure. After the new pipeline system is used and verified, the old edxapp pipeline system can be removed.
I modified the cd_edxapp.py script to be able to make build-only, M/D-only, or B/M/D pipelines, instead of breaking that up into three different scripts.
An approximation of what this pipeline system looks like can be seen on the tools GoCD instance in the `jeskew_test` pipeline group. …
> Build edxapp production AMIs earlier in pipeline.

- config.yml
- edxpipelines/pipelines/cd_edxapp_latest.py
Follow-on for work on this ticket:
https://openedx.atlassian.net/browse/TE-1789
This change fixes the creation of duplicate pipelines for the ones currently in use. After the other pipelines are converted to the new edxapp pattern, we'll retire the old version of cd_edxapp.py.
@edx/pipeline-team Please review.
> Bring back old version of cd_edxapp.py for non-converted pipelines.

- edxpipelines/patterns/stages.py
- edxpipelines/patterns/tasks.py
- edxpipelines/pipelines/cd_edxapp_latest.py
@edx/pipeline-team @jibsheet PTAL. This is the fix for https://openedx.atlassian.net/browse/TE-1868 we experienced during the release today.
> M/D pipelines will now get the AMI_ID to launch from the upstream B pipeline

- config.yml
@feanil @doctoryes This will fix the pipeline automation failure.
We were passing an incorrect variable file to the prod-edge-edxapp-private rollback pipeline.
> correct input variables for edxapp-edge-private-rollbackup pipeline

- edxpipelines/pipelines/prerelease_materials.py
@edx/pipeline-team PTAL, this is part 1/2 for continuous delivery of edxapp to stage.
cc: @cpennington 
part 2/2: https://github.com/edx-ops/gomatic-secure/pull/83
> Add check for key continuous_delivery and do not put in ignore patterns for a material

- edxpipelines/constants.py
- edxpipelines/patterns/stages.py
- edxpipelines/pipelines/cd_edxapp_latest.py
- edxpipelines/pipelines/prerelease_materials.py
https://openedx.atlassian.net/browse/TE-1814
The base AMI ID to use in building new AMIs will now be determined in the prerelease stage. The logic used to determine the base AMI ID will now be the same as the logic used in Alton. Uses the code introduced in this PR:
https://github.com/edx/tubular/pull/81
The new way that base AMI selection will work:
- If you simply run the prerelease pipeline via the "Play" button, the base AMI will be determined via looking at the active EDP cluster and choosing the same AMI that is active there.
- If you'd like to use an AMI of your own choosing, click the "Play Plus" button, set `BASE_AMI_ID_OVERRIDE` to "yes", and set `BASE_AMI_ID` to the AMI ID you'd like to use.
- If you'd like to fall-back to use the AMI ID specified in the config file, click the …
> Add base AMI selection phase in prerelease pipeline.

- edxpipelines/constants.py
- edxpipelines/patterns/stages.py
- edxpipelines/pipelines/cd_edxapp_latest.py
- edxpipelines/pipelines/prerelease_materials.py
The changes in this PR have been merged and reverted before, due to an error in running the Gomatic. The error was caused by removing a stage that was an upstream dependency of three different pipelines. Here's the history:
The original PR (with details of how the feature works):
https://github.com/edx/edx-gomatic/pull/101
Fixes to the original PR - uncaught due to not attempting a test with `--dry-run` specified:
https://github.com/edx/edx-gomatic/pull/103
The code in this form still had a Gomatic error, which was:
```
Scripts failed:
INFO:root:script: {'bmd_steps': None,
'error': ['Traceback (most recent call last):',
'  File "edxpipelines/pipelines/prerelease_materials.py", line 123, in <module>',
'    install_pipelines()',
'  File …
```
> Add base AMI selection phase in prerelease pipeline (round 2)

- edxpipelines/pipelines/config/prod-edge-edxapp-latest.yml
- edxpipelines/pipelines/config/prod-edx-edxapp-latest.yml
The `PROD_{edx|edge}_edxapp_B` were *not* using the base AMI found by the base AMI selection code in the upstream prerelease pipeline - they were instead using the hard-coded base AMI IDs in the config files. After this change, those pipelines will use the same base AMI that's used in the `STAGE_edxapp_B-M-D` pipeline. This is a bug fix for the original base AMI selection changes.
> Add upstream_ami_selection section to prod edx/edge files as well.

- edxpipelines/pipelines/config/prod-edge-edxapp-latest.yml
- edxpipelines/pipelines/config/prod-edx-edxapp-latest.yml
Reverts edx/edx-gomatic#114
The base AMI selection code needs to grab the AMI IDs for each EDP separately instead of using a common AMI_ID. Until the code is changed to do so, reverting this change.
> Revert "Add upstream_ami_selection section to prod edx/edge files as well."

- edxpipelines/constants.py
- edxpipelines/patterns/edxapp.py
- edxpipelines/patterns/stages.py
- edxpipelines/patterns/tasks.py
- edxpipelines/pipelines/cd_edxapp_latest.py
- edxpipelines/pipelines/config/edxapp.yml
- requirements/test_requirements.txt
Part of: https://openedx.atlassian.net/browse/TE-1739
Blocked until merging of this PR:
https://github.com/edx/tubular/pull/99
Adds a separate pipeline to the edxapp pipeline system whose upstream dependencies are the prod deployment pipelines. The pipeline has three stages which perform the following functions:
* fast-forward merge the release-candidate branch into the release branch
* create a branch off release and create PR to merge the new branch to master
* poll PR tests until they pass/fail and, upon success, merge the PR
> Add branch merging and tagging into edxapp pipeline.

- edxpipelines/patterns/edxapp.py
- edxpipelines/patterns/stages.py
- edxpipelines/patterns/tasks.py
- edxpipelines/pipelines/cd_edxapp_latest.py
Instead of using a different time for the tag upon each time the tagging stage is re-run, use the deploy artifact to use a consistent time.
Depends on: https://github.com/edx/tubular/pull/111
> Send deploy artifact to tag creation script for deploy time.

- edxpipelines/patterns/tasks.py
> Remove extra space in PR polling call.

- edxpipelines/constants.py
- edxpipelines/patterns/stages.py
Adds a new stage that can be used to build/serialize the value_stream_map url for a pipeline/label.
Full disclosure: I'm not very familiar with this repository and how everything fits together. Please review carefully and let me know if anything needs to be changed.
JIRA: https://openedx.atlassian.net/browse/TE-1937
> TE-1937 create build_value_stream_map_url stage

- edxpipelines/patterns/tasks.py
Doing this means that we don't need to prefix paths with '../' to get to
the artifact directory.
> Don't switch to a working directory when generating the wiki page.

- edxpipelines/patterns/edxapp.py
- edxpipelines/pipelines/cd_edxapp_latest.py
Have the migrations rollback pipeline use the AMI that was built during the build phase to rollback migrations.
> Fetch the rollback migrations ami artifact from the ami build step

- edxpipelines/patterns/stages.py
- edxpipelines/patterns/tasks.py
Not merging this will cause code to break the next time we deploy the agents.
> Execute install tubular scripts, rather than calling them via python2

- edxpipelines/patterns/edxapp.py
- edxpipelines/patterns/stages.py
- edxpipelines/patterns/tasks.py
- edxpipelines/pipelines/cd_edxapp_latest.py
This prevents the commit being released from being lost when the new
release-candidate is cut. However, this will require a janitor job to
deal with any releases that are never completed.
> Create a new branch for each release candidate

- config.yml
- edxpipelines/constants.py
- edxpipelines/patterns/stages.py
- edxpipelines/patterns/tasks/common.py
- edxpipelines/pipelines/instance_cleanup.py
I put some of the config for variables we may want to tweak directly in the pipeline script code. Where do we want to store stuff like this?
> Pipelines to cleanup dangling EC2 instances

- edxpipelines/patterns/edxapp.py
This should prevent a race-condition where edx-platform-private hasn't been updated yet after edx-platform changes.
> Only trigger prerelease_edxapp_materials_latest on edx-platform-private changes

- edxpipelines/patterns/edxapp.py
This PR makes the creation of the new release candidate fail if it's not a fast-forward merge up from the old release candidate to master. This will keep us from losing commits on the release candidate, while also making sure we're always cutting new release candidates from master.
> Only cut the new r-c if it's a fast-forward from the old r-c

- edxpipelines/patterns/edxapp.py
Fixes this problem:
https://gocd.tools.edx.org/go/tab/build/detail/edxapp_release_advancer/3/advance_release/1/advance_release_job
The GoCD Python module we're using, yagocd, requires the method along with the FQDN.
> Add method to the GoCD url for release advancing.

- edxpipelines/patterns/stages.py
Fixes this error:
https://gocd.tools.edx.org/go/tab/build/detail/edxapp_release_advancer/4/advance_release/1/advance_release_job
Should be the last one for this rascally pipeline! 🔨
> Create the required artifact directory for release advancer.

- edxpipelines/pipelines/api_build.py
wget is no longer available on the go-agents.
> Convert wget commands to curl

- edxpipelines/materials.py
- edxpipelines/pipelines/deploy_marketing_site.py
- edxpipelines/pipelines/rollback_prod_marketing_site.py
- edxpipelines/pipelines/rollback_stage_marketing_site.py
Along with https://github.com/edx-ops/ecom-secure/pull/12/files this should unblock the release of the marketing site as well as remove all calls to RSA key formatting in tubular.
> Remove key formatting from marketing pipelines

- edxpipelines/patterns/tasks/common.py
Keeping RSA keys as encrypted variables in gocd was a bad idea. Lets put them in the go-agent images or other places, but no more of this. There will be a tubular PR to remove this code as well.
> remove format_RSA_key task

- edxpipelines/constants.py
- edxpipelines/materials.py
- edxpipelines/patterns/edxapp.py
- edxpipelines/patterns/pipelines.py
- edxpipelines/patterns/stages.py
- edxpipelines/patterns/tasks/common.py
- edxpipelines/pipelines/cd_edxapp_latest.py
https://openedx.atlassian.net/browse/TE-1738
The CI check happens after the armed stage in `manual_verification_edxapp_prod_early_ami_build`
This PR pairs well with:
https://github.com/edx/tubular/pull/164
> Add a job for each dependent repo to check CI tests.

- config.yml
- edxpipelines/patterns/edxapp.py
- edxpipelines/patterns/jobs.py
- edxpipelines/patterns/pipelines.py
- edxpipelines/pipelines/api_build.py
- edxpipelines/pipelines/api_deploy.py
- edxpipelines/pipelines/asg_cleanup.py
- edxpipelines/pipelines/build_ora2_sandbox.py
- edxpipelines/pipelines/cd_analyticsapi.py
- edxpipelines/pipelines/cd_credentials.py
- edxpipelines/pipelines/cd_discovery.py
- edxpipelines/pipelines/cd_ecommerce.py
- edxpipelines/pipelines/cd_ecomworker.py
- edxpipelines/pipelines/cd_edxapp.py
- edxpipelines/pipelines/cd_edxapp_latest.py
- edxpipelines/pipelines/cd_insights.py
- edxpipelines/pipelines/deploy_ami.py
- edxpipelines/pipelines/deploy_gomatic_pipelines.py
- edxpipelines/pipelines/deploy_marketing_site.py
- edxpipelines/pipelines/instance_cleanup.py
- edxpipelines/pipelines/manual_verification.py
- edxpipelines/pipelines/rollback_asgs.py
- edxpipelines/pipelines/rollback_prod_marketing_site.py
- edxpipelines/pipelines/rollback_stage_marketing_site.py
- edxpipelines/pipelines/script.py
- edxpipelines/tests/scripts/conftest.py
- edxpipelines/utils.py
This also cleans up how we manage configs, so that now you can have a single config dict that supplies a global view of non-environmental config values, but also gives you environmental config values if you ask using an EDP.
> Add the ability to pass env-deploy files at the commandline

- edxpipelines/patterns/edxapp.py
This reverts commit 9d59ed59a4e9be322cc5bf3efcf2e38351f63bce.
@feanil @cpennington @edx/release-pipeline
> Revert "Also capture the run in private as we do in edx-platform"

- edxpipelines/patterns/edxapp.py
- edxpipelines/patterns/stages.py
- edxpipelines/patterns/tasks/common.py
- edxpipelines/pipelines/build_ora2_sandbox.py
In conjunction with this I will turn on system wide job timeouts set @15 minutes.  Something to keep in mind is that a job will only timeout if there is no console activity, this isn't a kill if any job runs longer than 15 minutes type of thing.
Timeout docs:
https://docs.gocd.io/16.2.0/configuration/job_timeout.html
> Add timeouts to long running jobs.

- edxpipelines/tests/scripts/test_scripts.py
The updated test will now:
* Traverse all possible paths back back to artifacts that are ensured
* uses the correct pathing in the artifact pipeline name when fetching an artifact that is more than one hop in the graph.
> Testing fetchartifacts now respects the upstream pipelines path

- edxpipelines/patterns/edxapp.py
- edxpipelines/patterns/stages.py
- edxpipelines/pipelines/cd_edxapp_latest.py
- edxpipelines/tests/scripts/test_scripts.py
- edxpipelines/utils.py
This PR is part of the work for [TE-2050](https://openedx.atlassian.net/browse/TE-2050). Many materials for pipelines have been removed in favor of fetching them [via an ancestor in the gocd graph.](https://docs.gocd.io/17.4.0/configuration/managing_dependencies.html) 
This should simplify the value stream map view for edxapp and simplify pipeline triggering (as the user will no longer need to look through multiple PipelineMaterial dependencies to figure out why a pipeline has not fired).
@cpennington something I was unsure about was the passing of the AMI pairs to the wiki page generator on rollback. I am currently only passing the rolled back AMI pair (edge or edx) instead of both. Will the wiki page generator still work correctly with only the rolled back environment info or does it …
> Refactor upstream artifacts for edxapp

- edxpipelines/patterns/edxapp.py
- edxpipelines/patterns/tasks/common.py
This will output a URL to assist pipeline operators in troubleshooting e2e test failures.
> Add troubleshooting help to e2e tests on failure

- edxpipelines/patterns/tasks/common.py
FYI @rlucioni @doctoryes 
This will add the stage counter to the AMI name. This will ensure a unique name for each AMI built if a stage is re-run. 
Prevents AMIs from not being built if there is a duplicate name.
> Add stage counter to AMI names

- edxpipelines/patterns/edxapp.py
- edxpipelines/pipelines/cd_edxapp_latest.py
Adding fred as a reviewer on this as an FYI since he is devops on call this week.
This will repair rollback in edxapp when ASGs still exist. I have another fix forthcoming to deal with the AMI issue.
> edxapp rollback now uses correct deploy artifact

- deploy_pipelines.py
- edxpipelines/constants.py
- edxpipelines/patterns/jobs.py
- edxpipelines/patterns/pipelines.py
- edxpipelines/patterns/tasks/common.py
- edxpipelines/pipelines/cd_ecommerce.py
Service deployment pipelines can now be configured to run
end-to-end/acceptance tests after continuous deployment pipelines deploy
AMIs. This new stage will execute a remote Jenkins job.
This functionality has been enabled for the E-Commerce Service.
LEARNER-509
> Added stage to run end-to-end tests

- requirements.txt
Now that the official repo is updated, we no longer need our own fork.
LEARNER-509
> Pulling Gomatic from the official repo
