.pep8, .travis.yml, edxpipelines/patterns/pipelines.py, edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks.py, edxpipelines/pipelines/asg_cleanup.py, edxpipelines/pipelines/build_edxapp_ami.py, edxpipelines/pipelines/cd_programs.py, edxpipelines/pipelines/deploy_ami.py, edxpipelines/tests/test_utils.py, edxpipelines/utils.py, requirements/test_requirements.txt, reverse_engineer.py
Add PEP8 config and requirement. Add Travis config to run pep8.
=> Refactor build/migrate/deploy pipeline into patterns.

edxpipelines/patterns/tasks.py
=> Adding generic task for fetching a secure private repo

edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks.py, edxpipelines/pipelines/cd_programs.py, edxpipelines/pipelines/cd_programs_multistage.py
=> generic ida play pattern

config.yml, deploy_pipelines.py, edxpipelines/patterns/pipelines.py, edxpipelines/patterns/stages.py, edxpipelines/pipelines/asg_cleanup.py
@edx/pipeline-team Please review. 
Note the output log formatting still need some help if you have any ideas.
=> Adding script to execute batches of gomatic pipelines

config.yml
@edx/pipeline-team @Dillon-Dumesnil PTAL. There is an accompanying PR in secure that goes with this.
=> removing common.yml from all scripts 

edxpipelines/patterns/tasks.py
@feanil @Dillon-Dumesnil PTAL.
=> Fix regression with target directory creation when checking out secure repos

edxpipelines/constants.py, edxpipelines/pipelines/deploy_marketing_site.py, edxpipelines/pipelines/rollback_prod_marketing_site.py, edxpipelines/pipelines/rollback_stage_marketing_site.py
@edx/pipeline-team Please review
=> Switched the group to E-Commerce

edxpipelines/pipelines/deploy_marketing_site.py, edxpipelines/pipelines/rollback_prod_marketing_site.py, edxpipelines/pipelines/rollback_stage_marketing_site.py
@edx/pipeline-team Please review
=> Reordered the stages so clearing caches comes after deploying.

deploy_pipelines.py, edxpipelines/pipelines/asg_cleanup.py, edxpipelines/pipelines/build_edxapp_ami.py, edxpipelines/pipelines/cd_programs_multistage.py, edxpipelines/pipelines/deploy_ami.py, edxpipelines/pipelines/deploy_gomatic_pipelines.py, edxpipelines/pipelines/deploy_marketing_site.py, edxpipelines/pipelines/rollback_prod_marketing_site.py, edxpipelines/pipelines/rollback_stage_marketing_site.py
=> Be able to run deploy_pipelines.py in dry_run mode.

Makefile
=> Add test targets.

Makefile, config.yml, edxpipelines/pipelines/api_build.py, edxpipelines/pipelines/api_deploy.py
@edx/pipeline-team @bilalahmad99 please review. I don't have permission to push to the edx/edx-gomatic repo so I went ahead and forked it for now.
=> initial checkin of api-manager pipeline group

config.yml, edxpipelines/patterns/stages.py
=> Enable deploy-..-ami gomatic.

config.yml
=> Move ASG cleanup scripts to use the shared deployment credentials.

config.yml, edxpipelines/pipelines/cd_edxapp.py
@edx/pipeline-team PTAL.
This is the work for TE-1625 - Create a gocd pipeline for edxapp stage
https://github.com/edx-ops/gomatic-secure/pull/31 must be merged first.
=> Edxapp pipeline for stage

edxpipelines/pipelines/api_deploy.py
=> adding a new stage in api manager pipeline for logging

.gitignore, edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks.py, edxpipelines/pipelines/cd_edxapp.py, edxpipelines/pipelines/cd_programs_multistage.py
The hipchat_token and hipchat_room values are now being properly sent to Ansible.
ECOM-5134
=> Fixed HipChat token issues

.gitignore, TODO.txt, config.yml, edxpipelines/patterns/pipelines.py, edxpipelines/patterns/tasks.py, edxpipelines/pipelines/cd_analyticsapi.py, edxpipelines/pipelines/cd_insights.py
@edx/pipeline-team @mulby @dsjen PTAL.
This will bring the analytic pipelines up to date with the latest gomatic changes. Please specifically check out the config.yml. What other pipelines should be deployed with the automation?
=> Analytics rebase

edxpipelines/constants.py, edxpipelines/pipelines/api_deploy.py
@jibsheet @doctoryes Allows configurable sleep wait time for tubular.
=> Add environment variable to configuar tubuar WAIT_SLEEP_TIME

config.yml
@edx/pipeline-team @maxrothman @e0d PTAL. Once merged this PR will deploy the production edxapp Build/Migrate/Deploy pipelines for all current deployments.
Pairs well with: https://github.com/edx-ops/gomatic-secure/pull/36
=> Adding deployments for prod-*-edxapp

config.yml
=> Added edx-private release pipelines

edxpipelines/patterns/pipelines.py, edxpipelines/patterns/stages.py, edxpipelines/pipelines/cd_edxapp.py, edxpipelines/pipelines/cd_programs_multistage.py
=> Multi-stage pipeline cleanup

config.yml, edxpipelines/pipelines/cd_ecommerce.py
=> Added pipeline for E-Commerce Service

config.yml
Restored missing anchor.
ECOM-5134
=> Fixed bug in config.yml

edxpipelines/patterns/pipelines.py, edxpipelines/pipelines/cd_ecomworker.py
=> Skipping migrations for ecomworker

edxpipelines/constants.py, edxpipelines/patterns/stages.py
FYI: @doctoryes @jibsheet @clintonb
=> add tubular sleep_wait_time to all deploy stages

edxpipelines/patterns/pipelines.py
=> Added support for automatically deploying AMIs

edxpipelines/patterns/stages.py
More throttling, now for the deploy pipelines.
@doctoryes
=> Add sleep wait time for deploy pipelines.

edxpipelines/constants.py
@edx/pipeline-team PTAL. Once this is in we can turn on full automation for the ecom pipelines @clintonb @rlucioni
=> ignore Patterns regex must be a list of regexes

config.yml, edxpipelines/constants.py, edxpipelines/patterns/pipelines.py, edxpipelines/pipelines/cd_edxapp.py, edxpipelines/pipelines/manual_verification.py, edxpipelines/tests/test_utils.py
Pairs well with: https://github.com/edx-ops/gomatic-secure/pull/51
@doctoryes PTAL.
=> Link edx stage and prod enviroments to share git SHAs

edxpipelines/patterns/stages.py
=> add configuration install to instance cleanup stage pattern

edxpipelines/patterns/pipelines.py, edxpipelines/patterns/stages.py, edxpipelines/pipelines/cd_edxapp.py
Also fixed the tags for themes and config secure repositories.
@doctoryes PTAL. 
Pairs well with https://github.com/edx-ops/gomatic-secure/pull/54
=> Changes to deploy edxapp to environments other than edx (edge, etc)

config.yml, edxpipelines/constants.py, edxpipelines/patterns/stages.py, edxpipelines/pipelines/cd_credentials.py, edxpipelines/pipelines/cd_discovery.py, edxpipelines/pipelines/cd_ecommerce.py, edxpipelines/pipelines/cd_ecomworker.py, edxpipelines/pipelines/cd_edxapp.py, edxpipelines/pipelines/cd_programs.py, edxpipelines/pipelines/manual_verification.py, edxpipelines/pipelines/rollback_asgs.py
Pairs well with a fine chanti *and* this PR:
https://github.com/edx-ops/gomatic-secure/pull/55
@edx/pipeline-team Please review.
=> Add gomatic code to create ASG rollback pipelines.

edxpipelines/constants.py, edxpipelines/pipelines/manual_verification.py
@doctoryes PTAL.
There will be conflicts with your other PR. Please review this, we will merge your PR first then I will rebase and pull this in.
=> First stage of manual verification is now automatic

edxpipelines/pipelines/cd_edxapp.py
=> Change the user that runs the edxapp migrations

edxpipelines/pipelines/cd_insights.py
@maxrothman @dsjen @thallada
This will fix the insights version deployment issue.
=> Make insights pipelines use the correct version variable

edxpipelines/pipelines/cd_analyticsapi.py
=> update analytics api version variable name

edxpipelines/pipelines/cd_credentials.py, edxpipelines/pipelines/cd_discovery.py, edxpipelines/pipelines/cd_ecommerce.py, edxpipelines/pipelines/cd_ecomworker.py, edxpipelines/pipelines/cd_insights.py, edxpipelines/pipelines/cd_programs.py
=> Mark --save-config and --dry-run as flags so you can use them

edxpipelines/patterns/pipelines.py, edxpipelines/patterns/stages.py, edxpipelines/pipelines/cd_edxapp.py
@edx/pipeline-team @maxrothman PTAL. TE-1742
Consolidates 2 different ami deployment stage patterns in to a single pattern.
=> Consolidate deploy stages in to a single pattern

edxpipelines/patterns/pipelines.py, edxpipelines/patterns/stages.py, edxpipelines/pipelines/cd_edxapp.py
Reverts edx/edx-gomatic#75
@doctoryes @e0d FYI.
=> Revert "Consolidate deploy stages in to a single pattern"

edxpipelines/patterns/pipelines.py, edxpipelines/patterns/stages.py, edxpipelines/pipelines/cd_edxapp.py
@edx/pipeline-team PTAL.
environment variables will now be interpolated by bash.
=> Change deploy interpreter to use bash

edxpipelines/patterns/stages.py, edxpipelines/pipelines/deploy_ami.py
=> deploy fixes

edxpipelines/pipelines/cd_analyticsapi.py, edxpipelines/pipelines/cd_insights.py
=> ensure app_version on analytics api pipelines.

edxpipelines/patterns/stages.py
=> put ami.yml in the correct place to launch an instance using the correct file name.

README.md
This is becoming a more common question. Calling it out clearly is helpful when getting started.
@clintonb @edx/pipeline-team
=> Update README to make it clear that this code is written in Python 2.7

README.md
Addressing @clintonb's feedback. @macdiesel you merged so fast last time I didn't get a chance to push this up!
=> Specify 2.7.x instead of 2.7+, for clarity

edxpipelines/pipelines/prerelease_materials.py
=> improved pre-release materials ignore detection

config.yml, edxpipelines/pipelines/cd_edxapp_latest.py
@edx/pipeline-team Please review - though I'm going to go ahead and merge.
=> Fix errors with gomatic for base AMI selection in prerelease stage.

edxpipelines/pipelines/prerelease_materials.py
=> Fix revert - put back in armed stage in prerelease.

edxpipelines/constants.py, edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks.py
=> Add stage and task pattern to create a branch and pull request.

config.yml, edxpipelines/constants.py, edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks.py, edxpipelines/pipelines/cut_branch.py
@edx/pipeline-team @cpennington PTAL.
Serve with: edx-ops/gomatic-secure/pull/95
=> New pipeline to create a branch on a schedule

edxpipelines/pipelines/manual_verification.py
=> Add missing import statement to manual verification pipeline

edxpipelines/patterns/pipelines.py, edxpipelines/patterns/stages.py
=> Add base AMI-ID selection to IDAs

edxpipelines/patterns/pipelines.py
=> move manual approval up to the new first stage for IDA pipelines

edxpipelines/patterns/stages.py, edxpipelines/pipelines/cut_branch.py
@edx/pipeline-team @cpennington PTAL.
=> Set first stage of cut RC to manual so the cron timer will trigger correctly

edxpipelines/patterns/stages.py
=> remove bool

edxpipelines/materials.py, edxpipelines/pipelines/cd_edxapp_latest.py, edxpipelines/pipelines/edxapp_pipelines.py
=> Remove McKinsey materials from edxapp pipelines

edxpipelines/constants.py, edxpipelines/patterns/edxapp.py, edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks.py
@edx/pipeline-team PTAL.
I will integrate these in to the edxapp pipelines once @cpennington 's atomic PR lands. #118
=> Gomatic stage patterns to message pull requests

edxpipelines/patterns/edxapp.py
=> moar commas

edxpipelines/pipelines/cd_edxapp_latest.py
=> Fix stage migrate/deploy pipeline to fetch correct launch AMI

edxpipelines/patterns/edxapp.py, edxpipelines/patterns/stages.py, edxpipelines/pipelines/config/edxapp.yml
Pull the polling params out into a YAML file and make them realistic for edx-platform CI. I meant to do this in the original PR.
=> Adjust the test-polling params for edx-platform branch merging.

deploy_pipelines.py, edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks.py, edxpipelines/pipelines/deploy_gomatic_pipelines.py, tox.ini
Requires https://github.com/edx/tubular/pull/114
=> Use shebangs, rather than passing scripts to python

deploy_pipelines.py, edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks.py, edxpipelines/pipelines/deploy_gomatic_pipelines.py, tox.ini
This reverts commit 63484c4370be1d956b53f9b5584d9630206747bd, reversing
changes made to ce0e3b0274e270552482771820e22151620b77d7.
=> Revert "Merge pull request #153 from edx/cale/use-shebangs"

edxpipelines/patterns/tasks.py
This reverts commit f5c8f0785c7ea3454c739f3ffe19e9897d0b57bc, reversing
changes made to 6a17de11bed8003be7b4bf5ebdbca01198f2b6cf.
=> Revert "Merge pull request #158 from edx/cale/install-requirements-py3"

edxpipelines/constants.py, edxpipelines/patterns/edxapp.py, edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks.py, edxpipelines/pipelines/config/edxapp.yml, requirements/test_requirements.txt
https://openedx.atlassian.net/browse/TE-1885
Calls the tubular script which checks the duration of a stage edxapp migration and alerts via email when threshold is crossed.
=> Gomatic to check migration durations

edxpipelines/patterns/tasks.py
@cpennington @edx/pipeline-team Please review.
=> Change command-line param name for file.

edxpipelines/constants.py
Changed to check the "default" database. I'll add the checking of the "CSMH" database to this ticket:
https://openedx.atlassian.net/browse/TE-1925
@cpennington @edx/pipeline-team Please review.
=> Change filename to check the default migration.

edxpipelines/patterns/tasks.py
We chose to put the migrations artifacts in this directory.
@cpennington @edx/pipeline-team Please review.
=> Add the missing migrations directory.

edxpipelines/pipelines/cd_ecomworker.py
=> Corrected the playbook and repo for ecomworker

edxpipelines/patterns/tasks.py, edxpipelines/pipelines/deploy_marketing_site.py, edxpipelines/pipelines/rollback_prod_marketing_site.py, edxpipelines/pipelines/rollback_stage_marketing_site.py
I noticed that we generate `ExecTasks` in ways that are fairly standard, but are mostly copy/paste/convention right now. So, I thought I'd try pulling them out into separate functions. Let me know what you think, and whether this refactor is worth merging.
=> Extract common ExecTasks into separate functions

edxpipelines/patterns/tasks.py
=> correct migration rollback task command line

edxpipelines/patterns/tasks.py
=> Put the input release_page_id.yml file into a named folder

edxpipelines/patterns/edxapp.py, edxpipelines/patterns/pipelines.py, edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks.py, edxpipelines/pipelines/cd_edxapp.py, edxpipelines/pipelines/cd_edxapp_latest.py, edxpipelines/tests/scripts/test_scripts.py, edxpipelines/utils.py
This also packages up the e-d-p as a named tuple, since it is almost always passed together (as 3 separate arguments) to functions that need it.
=> Check for undefined environment variables

edxpipelines/patterns/jobs.py, edxpipelines/patterns/pipelines.py, edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks.py
This attempts to codify the responsibilities of each pattern type. We have patterns that violate these proposed rules, which we'd likely want to fix in due course. But I wanted to at least get the principles out there for discussion.
=> Add documentation about what each type of pattern is responsible for

edxpipelines/pipelines/cd_edxapp_latest.py
Adding the ability to rollback migrations in the staging environment for edxapp.
=> Add stage migrations rollback pipeline

config.yml, edxpipelines/constants.py, edxpipelines/pipelines/build_ora2_sandbox.py
Utilizes the Jenkins Task Pattern to trigger jobs on Tools Jenkins.
Depends upon credentials in https://github.com/edx-ops/gomatic-secure/pull/115
=> Adds in pipeline and tasks for ora2 sandbox creation

edxpipelines/constants.py, edxpipelines/patterns/edxapp.py, edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks/common.py, edxpipelines/pipelines/cd_edxapp_latest.py
Also, some HipChat messaging changes.
=> Add new pipeline to automatically advance edxapp to production.

edxpipelines/patterns/stages.py
Fixes the problem here:
https://gocd.tools.edx.org/go/tab/build/detail/edxapp_release_advancer/1/advance_release/1/advance_release_job
along with the accompanying PR here:
https://github.com/edx/tubular/pull/159
=> Add missing tubular pkg install.

edxpipelines/patterns/tasks/common.py
Fixes this issue:
https://gocd.tools.edx.org/go/tab/build/detail/edxapp_release_advancer/2/advance_release/1/advance_release_job
=> Change hipchat_room to hipchat_channel as script expects.

edxpipelines/materials.py, requirements.txt
This reverts commit ab6b8cd57575d8ec55d1d5e350f40e92649441e9.
=> Revert "Make clones of git materials shallow"

edxpipelines/constants.py, edxpipelines/patterns/edxapp.py, edxpipelines/patterns/jobs.py, edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks/common.py, edxpipelines/pipelines/cd_edxapp_latest.py
=> Move AMI selection back to prerelease

edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks/common.py
Fixes this failure:
https://gocd.tools.edx.org/go/tab/build/detail/edxapp_release_advancer/5/advance_release/1/advance_release_job
=> Fix path to written artifact and remove some envvars.

config.yml, edxpipelines/materials.py, edxpipelines/patterns/tasks/common.py, edxpipelines/pipelines/deploy_marketing_site.py, edxpipelines/pipelines/rollback_prod_marketing_site.py, edxpipelines/pipelines/rollback_stage_marketing_site.py, edxpipelines/tests/scripts/test_scripts.py
@schenedx this will replace #274
=> Deprecate _fetch_secure_repo

edxpipelines/pipelines/deploy_marketing_site.py, edxpipelines/pipelines/rollback_prod_marketing_site.py, edxpipelines/pipelines/rollback_stage_marketing_site.py
=> marketing deploy remote and key fixes

edxpipelines/pipelines/deploy_marketing_site.py, edxpipelines/pipelines/rollback_prod_marketing_site.py, edxpipelines/pipelines/rollback_stage_marketing_site.py
=> fix private key chmod pathing

edxpipelines/constants.py, edxpipelines/pipelines/build_ora2_sandbox.py
Utilizes the Jenkins Task Pattern to trigger jobs on Tools Jenkins. Adds in run test and add course to sandbox to the pipeline.
=> TNL-6390: Adds run test and add course tasks to ora2 pipeline

edxpipelines/pipelines/deploy_marketing_site.py
@edx/pipeline-team @amangano-edx FYI.
=> Add semicolon to statements in if block

edxpipelines/patterns/edxapp.py
I had to modify the job's task and re-run it this morning to get the stage to pass:
https://gocd.tools.edx.org/go/pipelines/edxapp_branch_cleanup/73/merge_rc_branch/2
This PR contains what I changed.
=> Change variable name for which to search - dashes to underscores.

edxpipelines/materials.py, requirements.txt
This reverts commit 3bc4d0b5fa6477730129cadf1bde727ee07a2950.
=> Make clones of git materials shallow

edxpipelines/materials.py, edxpipelines/pipelines/build_ora2_sandbox.py
Adds in a daily timer trigger as well as a Git material to trigger on pushes to edx-ora2 master. Additionally sets defaults for the dns and name environment variables for the timer material of the pipeline to execute with.
FYI: @staubina @cahrens
=> TNL-6389: Adds in triggers for ORA2 Jobs

edxpipelines/patterns/edxapp.py, edxpipelines/pipelines/cd_edxapp_latest.py
https://openedx.atlassian.net/browse/TE-2050
=> Manual verification pipeline should depend on the deploy stage

edxpipelines/patterns/edxapp.py, edxpipelines/pipelines/cd_edxapp_latest.py
Error came up during deployment, rolling this back until I can troubleshoot it better.
=> Revert "Manual verification pipeline should depend on the deploy stage"

edxpipelines/patterns/edxapp.py
@feanil
FYI @cpennington
FYI @edx/pipeline-team
=> Also capture the run in private as we do in edx-platform

edxpipelines/pipelines/cd_analyticsapi.py
=> correct analytics_api play name

edxpipelines/patterns/jobs.py
=> Make the application name match the application_user for running migrations

edxpipelines/constants.py, edxpipelines/materials.py, edxpipelines/patterns/edxapp.py, edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks/private_releases.py, edxpipelines/pipelines/cd_edxapp_latest.py
https://openedx.atlassian.net/browse/TE-1991
The two pipeline stages do the following:
- create a PR merging any private commits to public repo
- poll the PR tests, merge the PR, and push result back to private repo.
The pipeline will be triggered on any merges into the `security_release` branch in the edx-platform-private repo.
=> Add two-stage pipeline to merge commit between public/private repos.

edxpipelines/materials.py, edxpipelines/patterns/edxapp.py, edxpipelines/patterns/tasks/private_releases.py
- Change to proper private repo URL.
- Change/remove incorrect script params.
=> Minor fixes found upon first pipeline run.

edxpipelines/patterns/edxapp.py
=> Remove the reference repos, since they are shallow materials.

edxpipelines/patterns/stages.py, edxpipelines/patterns/tasks/common.py, requirements.txt
Step one to updating the asgard token.
=> Update ASGARD_API_TOKEN to an unencrypted_secure variable
